import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
import styled from 'styled-components'
import SectionCeremonyAndParty from '../components/SectionCeremonyAndParty'

const BgImage = dynamic(() => import("../components/BGImage"), {
  ssr: false
})

const SectionPortadaImage = styled.section`
display: flex;
justify-content: center;
align-items: center;
height: 100vh;
`

// opt-out of image optimization, no-op
const customLoader = ({ src }) => {
  return src
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Wedding App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BgImage />
      <SectionPortadaImage>
        <div className={styles.portada}>
          <Image src='/logo-portada.png' width={500} height={500} alt='logo' loader={customLoader} />
          <div className={styles.arrow} />
        </div>
      </SectionPortadaImage>
      <SectionCeremonyAndParty />
    </>
  )
}
