import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
import styled from 'styled-components'

const BgImage = dynamic(() => import("../components/BGImage"), {
  ssr: false
})

const SectionPortadaImage = styled.section`
display: flex;
justify-content: center;
align-items: center;
height: 100vh;
`

const SectionInfo = styled.section`
    font-weight: 400;
    line-height: 1.5;
    color: #212529;
    text-align: left;
    background-color: #fff;
    font-family: 'Montserrat', sans-serif;
    font-size: 17px;
    height: 400px;
    position: absolute;
    width: 100%;
    `
// opt-out of image optimization, no-op
const customLoader = ({ src }) => {
  return src
}

const Button = styled.button`
border: none; 
color: white; 
padding: 16px 32px; 
text-align: center; 
text-decoration: none; 
font-size: 16px; 
margin: 4px 2px; 
cursor: pointer;
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Wedding App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BgImage />
      <SectionPortadaImage>
        <Image src='/logo-portada.png' width={500} height={500} alt='logo' loader={customLoader} />
      </SectionPortadaImage>
      <SectionInfo>
        <div className='container'>
          <div className='row'>
            <div className='col-md-6 columna'>

            </div>
            <div className='col-md-6 columna'>
              <Button>{'Hola'}</Button>
            </div>

          </div>
        </div>
      </SectionInfo>
    </>
  )
}
